2021-10-06 14:47:27,427:__main__:Failed to open the main Window
Traceback (most recent call last):
  File "c:/Users/DE1119189/Desktop/Github/Fileserve_Observer/src/main.py", line 26, in <module>
    mtain()
NameError: name 'mtain' is not defined
2021-10-06 14:50:15,421:root:Failed to open the main Window
Traceback (most recent call last):
  File "c:/Users/DE1119189/Desktop/Github/Fileserve_Observer/src/main.py", line 30, in <module>
    mtain()
NameError: name 'mtain' is not defined
